
/*
 * CommandCodes.h
 *
 *  Created on: 21/06/2022
 *      Author: jmotp
 */

#ifndef TRANSDUCERSERVICES_COMMANDCODES_H_
#define TRANSDUCERSERVICES_COMMANDCODES_H_

#define COMMON_CMD 1
#define XDCR_OPERATE 3

#define READ_TEDS_SEGMENT 2



#define READ_TRANSDUCERCHANNEL_DATA 1

#endif /* TRANSDUCERSERVICES_COMMANDCODES_H_ */
